== hola ==

In [2]:
import glob
import os
import shutil
import pandas as pd

src_fldr=r"/media/documentos/Cursos/Data Science/Python/Data_Science_Python/data_sets/"
dst_fldr=r"/media/documentos/Cursos/Data Science/Python/Data_Science_Python/data_sets/Proc/"
pattern = "*.pkl"

# Search files with .docx extension in source directory

files = glob.glob(src_fldr + pattern)
print(files)
# move the files with txt extension
for file in files:
    df=pd.DataFrame()
    # extract file name form file path
    file_name = os.path.basename(file)
    r_file = file_name.split(".")[0]+'.csv'
    df=pd.read_pickle(src_fldr+file_name)
    df.to_csv(dst_fldr+r_file)


['/media/documentos/Cursos/Data Science/Python/Data_Science_Python/data_sets/avoplotto.pkl']


In [1]:
import numpy as np

x = np.array([9, 5])
y = np.array([16, 12])

print(np.logical_or(x < 5, y > 15))

[ True False]


In [2]:
escape_velocity = {
    'earth': 1,
    'mercury': 0.384,
    'mars': 0.450
}

del(escape_velocity["mars"] )
print(escape_velocity)

{'earth': 1, 'mercury': 0.384}


In [5]:
flash_vil = ['Mick Rory', 'Leonard Snart', 'Gorilla Grodd']
for x , y in  enumerate(flash_vil):
    print(str(x)+ ': ' + y)

0: Mick Rory
1: Leonard Snart
2: Gorilla Grodd


In [8]:
x = [1, 'A', 2, 'B', 3, 'C']
strings = [y  for y in x if type(y) == str]
print(strings)

['A', 'B', 'C']


In [9]:
characters_names = ['Felicity Smoak', 'Laurel Lance']
code_names = ['Overwatch', 'Black Canary']

team_arrow = zip(characters_names,code_names)

for i,j in team_arrow:
    print (i + 'is the ' + j )

Felicity Smoakis the Overwatch
Laurel Lanceis the Black Canary


In [1]:
import numpy as np
np_heights = np.array([[1.60,1.75],[1.56,1.70],[1.49,1.68]])
print(np.corrcoef(np_heights[:,0], np_heights[:,1]))

[[1.         0.92155064]
 [0.92155064 1.        ]]


In [2]:
import numpy as np
array_2D = np.array([[ 5,  1,  3,  2,  4,  6],
       [ 5,  8,  0,  3,  1,  2],
       [ 3, 10,  6, 21, 15,  1]])

print(array_2D[array_2D>7])

[ 8 10 21 15]


In [4]:
import numpy as np
array_2D = np.array([[ 5,  1,  3,  2,  4,  6],
       [ 5,  8,  0,  3,  1,  2],
       [ 3, 10,  6, 21, 15,  1]])

print(np.sort(array_2D,axis=0))

[[ 3  1  0  2  1  1]
 [ 5  8  3  3  4  2]
 [ 5 10  6 21 15  6]]


In [7]:
import numpy as np
array_2D = np.array([[ 1,  2,  3,  4,  5,  6],
       [ 0,  1,  2,  3,  5,  8],
       [ 1,  3,  6, 10, 15, 21]])

print(array_2D[:, 0:7:3])

[[ 1  4]
 [ 0  3]
 [ 1 10]]


In [11]:
temp = 15
def convert_temp(x):
    """Converts the temperature from Celsius to Fahrenheit"""
    global temp
    temp = (x * 1.8) + 32

convert_temp(temp)
print(temp)

59.0


In [30]:
def add_zeros(string):
    """Returns a string padded with zeros
       to ensure consistent length"""
    updated_string = string + '0'
    def add_more():
        """Adds more zeros if necessary"""
        nonlocal updated_string
        updated_string = updated_string + '0'
        while len(updated_string) < 6:
            add_more(updated_string)
    return updated_string
    #1.2000  45.670
add_zeros('1.2')#, add_zeros('45.67')

'1.20'

In [33]:
x = ['aPPle','baNANa']
def caps(li):
    """returns a list , with all elements capitalized"""
    def inner (w):
        """return a capitalized word"""
        return w.capitalize()
    return ([inner(li[0]),inner(li[1])])
            
print(caps(x))

['Apple', 'Banana']


In [2]:
import numpy as np
rgb =np.array([[[255,   0,   0],
        [  0,   0,   0],
        [  0,   0, 255]],

       [[255,   0, 255],
        [255, 255, 255],
        [255, 255,   0]]])

np.flip(rgb)

array([[[  0, 255, 255],
        [255, 255, 255],
        [255,   0, 255]],

       [[255,   0,   0],
        [  0,   0,   0],
        [  0,   0, 255]]])

In [1]:
import numpy as np
arr_1 = np.array([[2, 0, 1], [9, 1, 4]])
arr_2 = np.array([[3, 8, 8], [5, 2, 0]])

np.stack([arr_1, arr_2], axis=2)

array([[[2, 3],
        [0, 8],
        [1, 8]],

       [[9, 5],
        [1, 2],
        [4, 0]]])

In [2]:
import numpy as np
rgb=np.array([[[255,   0,   0],
        [  0,   0,   0],
        [  0,   0, 255]],

       [[255,   0, 255],
        [255, 255, 255],
        [255, 255,   0]]])

np.transpose(rgb)

array([[[255, 255],
        [  0, 255],
        [  0, 255]],

       [[  0,   0],
        [  0, 255],
        [  0, 255]],

       [[  0, 255],
        [  0, 255],
        [255,   0]]])

In [ ]:
import numpy as np


array([[[255,   0,   0],
        [  0,   0,   0],
        [  0,   0, 255]],

       [[255,   0, 255],
        [255, 255, 255],
        [255, 255,   0]]])

In [7]:
characters = ['The Hulk', 'Iron Man']
names = ['Bruce Banner', 'Tony Stark']
ave_1 = zip(characters, names)
avengers = list(ave_1)
print(avengers)

[('The Hulk', 'Bruce Banner'), ('Iron Man', 'Tony Stark')]


In [1]:
import numpy as np
x = [1, 2, 3, 4]
mult = { i: 3*i for i in x }
print(mult)

{1: 3, 2: 6, 3: 9, 4: 12}


In [2]:
floats = [9.33, 7.78, 3.16, 6.52]
integers = [round (x) for x in floats]
print(integers)

[9, 8, 3, 7]


In [4]:
numbers = [1, 2, 3, 4, 5]
times_ten = [n*10 for n in numbers]
times_ten

[10, 20, 30, 40, 50]

In [10]:
matrix= [[i+1 for i in range(3)] for x in range(3)]
print(matrix)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [3]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [1]:
txt = "Hello, And Welcome To My World!"
x = txt.casefold()
print(x)

hello, and welcome to my world!


In [4]:
x = [3, -1, -10, 2, 7]
filter_positives = list(filter(Lambda n:( n > 0), x))
print(list(filter_positives))

SyntaxError: invalid syntax (1275396511.py, line 2)

In [3]:
import numpy as np

rgb = np.array([[[255,   0,   0],
                 [  0,   0,   0],
                [  0,   0, 255]],

                  [[255,   0, 255],
                  [255, 255, 255],
                  [255, 255,   0]]])

arr_1, arr_2, arr_3 = np. split (rgb, 3, axis=1)
arr_1

array([[[255,   0,   0]],

       [[255,   0, 255]]])

In [6]:
arr_1 = np.array ([[2, 0, 1], [9, 1, 4]])
arr_2 = np.array([[3, 8, 8], [5, 2, 0]])
np.stack([arr_1, arr_2], axis=2)

array([[[2, 3],
        [0, 8],
        [1, 8]],

       [[9, 5],
        [1, 2],
        [4, 0]]])

In [8]:
rgb = np.array([[[255,   0,   0],
        [  0,   0,   0],
        [  0,   0, 255]],

       [[255,   0, 255],
        [255, 255, 255],
        [255, 255,   0]]])

np.flip(rgb, axis=(1, 2))

array([[[255,   0,   0],
        [  0,   0,   0],
        [  0,   0, 255]],

       [[  0, 255, 255],
        [255, 255, 255],
        [255,   0, 255]]])

In [4]:
import numpy as np
array_2D = np.array([[ 1,  2,  3,  4,  5,  6],
       [ 0,  1,  2,  3,  5,  8],
       [ 1,  3,  6, 10, 15, 21]])

array_2D[:, 0:7:3]

array([[ 1,  4],
       [ 0,  3],
       [ 1, 10]])

In [ ]:
x = [1, 'A', 2, 'B', 3, 'C']

strings = []

In [1]:
import numpy as np
array_2D=np.array([[ 5,  1,  3,  2,  4,  6],
       [ 5,  8,  0,  3,  1,  2],
       [ 3, 10,  6, 21, 15,  1]])

np.where(array_2D > 7)

NameError: name 'array_2D' is not defined