# 2D split and stack
Splitting and stacking skills aren't just useful with 3D RGB arrays: they are excellent for subsetting and organizing data of any type and dimension!

You'll now take a quick trip down memory lane to reorganize the `monthly_sales` array as a 3D array. Recall that the first dimension of `monthly_sales` is rows of a single month's sales across three industries, and the second dimension is columns of monthly sales data for a single industry.

Your task is to split this data into quarterly sales data and stack the quarterly sales data so that the new third dimension represents the four 2D arrays of quarterly sales.`numpy` is loaded as `np`, and the `monthly_sales` array is available.

In [4]:
import numpy as np
path=r"D:\\Cursos\\Data_Science_Python\\data_sets\\"
monthly_sales=np.load(path+"monthly_sales.npy")
display(monthly_sales.shape)
monthly_sales

(12, 3)

array([[ 4134, 23925,  8657],
       [ 4116, 23875,  9142],
       [ 4673, 27197, 10645],
       [ 4580, 25637, 10456],
       [ 5109, 27995, 11299],
       [ 5011, 27419, 10625],
       [ 5245, 27305, 10630],
       [ 5270, 27760, 11550],
       [ 4680, 24988,  9762],
       [ 4913, 25802, 10456],
       [ 5312, 25405, 13401],
       [ 6630, 27797, 18403]], dtype=int64)

* Split `monthly_sales` into four arrays representing quarterly data across industries; print `q1_sales`.

In [3]:
# Split monthly_sales into quarterly data
q1_sales, q2_sales, q3_sales, q4_sales = np.split(monthly_sales,4)
print(q1_sales)

[[ 4134 23925  8657]
 [ 4116 23875  9142]
 [ 4673 27197 10645]]


* Stack the four quarterly sales arrays to create a 3D array, `quarterly_sales`, made up of the four quarterly 2D arrays in order from the first to last quarter.

In [ ]:
# Split monthly_sales into quarterly data
q1_sales, q2_sales, q3_sales, q4_sales = np.split(monthly_sales, 4)

# Print q1_sales
print(q1_sales)

# Stack the four quarterly sales arrays
quarterly_sales = np.stack([q1_sales,q2_sales,q3_sales,q4_sales])
print(quarterly_sales)