# Filtering with masks
In the last lesson, you sorted trees from smallest to largest. Now, you'll use fancy indexing to return the row of data representing the largest tree in `tree_census`. You'll also examine other trees located on the same block as the largest tree: are they also large?

`numpy` is loaded as np, and the `tree_census` array is available. As a reminder, the `tree_census` columns in order refer to a tree's ID, its block ID, its trunk diameter, and its stump diameter.

In [5]:
import numpy as np
path=r"D:\\Cursos\\Data_Science_Python\\data_sets\\"
tree_census=np.load(path+"tree_census.npy")
display(tree_census.shape)

display(tree_census[0])

(1000, 4)

array([     3, 501451,     24,      0], dtype=int64)

* Using Boolean indexing, create an array, `largest_tree_data`, which contains the row of data on the largest tree in `tree_census` corresponding to the tree with a diameter of `51`.

In [6]:
# Create an array which contains row data on the largest tree in tree_census
largest_tree_data =tree_census[tree_census[:,2] == 51]
print(largest_tree_data)

[[    61 501882     51      0]]


* Slice largest_tree_data to retrieve only the block id of the block the largest tree is located on; save this block id as largest_tree_block_id.

In [9]:
# Create an array which contains row data on the largest tree in tree_census
largest_tree_data = tree_census[tree_census[:, 2] == 51]
print(largest_tree_data)

# Slice largest_tree_data to get only the block id
largest_tree_block_id = largest_tree_data[0,1]
print(largest_tree_block_id)

[[    61 501882     51      0]]
501882


* Using fancy indexing, create an array called `trees_on_largest_tree_block` which contains data on all trees with the same block ID as the largest tree.

In [20]:
# Create an array which contains row data on the largest tree in tree_census
largest_tree_data = tree_census[tree_census[:, 2] == 51]
print(largest_tree_data)

# Slice largest_tree_data to get only the block ID
largest_tree_block_id = largest_tree_data[:, 1]
print(largest_tree_block_id)

# Create an array which contains row data on all trees with largest_tree_block_id
trees_on_largest_tree_block = tree_census[tree_census[:,1]==largest_tree_block_id]
print(trees_on_largest_tree_block)

[[    61 501882     51      0]]
[501882]
[[    60 501882      8      0]
 [    61 501882     51      0]
 [    62 501882      7      0]
 [    63 501882      4      0]
 [    64 501882     15      0]
 [    65 501882      3      0]
 [    66 501882      8      0]
 [    67 501882      6      0]
 [    68 501882      6      0]
 [    69 501882      3      0]]
