# Fancy indexing vs. np.where()
You and your tree research team are double-checking collection data by visiting a few trees in person to confirm their measurements. You've been assigned to check the data for trees on block 313879, and you'd like to make a small array of just the tree data that relates to your work.

`numpy` is loaded as `np`, and the `tree_census` array is available. As a reminder, the `tree_census` columns in order refer to a tree's ID, its block ID, its trunk diameter, and its stump diameter.

In [1]:
import numpy as np
path=r"D:\\Cursos\\Data_Science_Python\\data_sets\\"
tree_census=np.load(path+"tree_census.npy")
display(tree_census.shape)

display(tree_census[0])

(1000, 4)

array([     3, 501451,     24,      0], dtype=int64)

* Using fancy indexing, create an array called `block_313879` which only contains data for trees with a block ID of 313879.

In [2]:
# Create the block_313879 array containing trees on block 313879
block_313879 = tree_census[tree_census[:,1]==313879]
print(block_313879)

[[  1115 313879      3      0]
 [  1116 313879     17      0]]


* Using `np.where()`, create an array of `row_indices` for trees with a block ID of 313879.
* Using `row_indices`, create `block_313879`, which contains data for trees on block 313879.

In [5]:
# Create an array of row_indices for trees on block 313879
row_indices = np.where(tree_census[:,1]==313879)

# Create an array which only contains data for trees on block 313879
block_313879 = tree_census[row_indices]
print(block_313879)

[[  1115 313879      3      0]
 [  1116 313879     17      0]]
