# Adding rows
The research team has discovered two trees that were left off the `tree_census`. Your task is to add rows containing the data for these new trees to the end of the tree_census array. The new trees' data is saved in a 2D array called new_trees:

`new_trees = np.array([[1211, 227386, 20, 0], [1212, 227386, 8, 0]])`

`numpy` is loaded as `np`, and the `tree_census` and `new_trees` arrays are available.

In [1]:
import numpy as np
path=r"D:\\Cursos\\Data_Science_Python\\data_sets\\"
tree_census=np.load(path+"tree_census.npy")
new_trees = np.array([[1211, 227386, 20, 0], [1212, 227386, 8, 0]])
display(tree_census.shape)

display(tree_census[0])
# its block ID, its trunk diameter, and its stump diameter.

(1000, 4)

array([     3, 501451,     24,      0], dtype=int64)

* Print the shapes of `tree_census` and `new_trees` to confirm they are compatible to concatenate.

In [2]:
# Print the shapes of tree_census and new_trees
print(tree_census.shape,new_trees.shape)

(1000, 4) (2, 4)


* Add rows to the end of `tree_census` containing data for the new trees from the `new_trees` 2D array; save the new array as `updated_tree_census`

In [7]:
# Print the shapes of tree_census and new_trees
print(tree_census.shape, new_trees.shape)

# Add rows to tree_census which contain data for the new trees
updated_tree_census = np.concatenate((tree_census,new_trees),axis=0)
print(updated_tree_census)

(1000, 4) (2, 4)
[[     3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 ...
 [  1210 227386      6      0]
 [  1211 227386     20      0]
 [  1212 227386      8      0]]
