# The speed of cats

You're working on a new web service that processes Instagram feeds to identify which pictures contain cats (don't ask why -- it's the internet). The code that processes the data is slower than you would like it to be, so you are working on tuning it up to run faster. Given an image, `image`, you have two functions that can process it:

* process_with_numpy(image)
* process_with_pytorch(image)

Your colleague wrote a context manager, `timer()`, that will print out how long the code inside the context block takes to run. She is suggesting you use it to see which of the two options is faster. Time each function to determine which one to use in your web service.

* Use the `timer()` context manager to time how long `process_with_numpy(image)` takes to run.
* Use the `timer()` context manager to time how long `process_with_pytorch(image)` takes to run.

In [12]:
import contextlib
import time
import numpy as np

@contextlib.contextmanager
def timer():
  """Time how long code in the context block takes to run."""
  t0 = time.time()
  try:
      yield
  except:
    raise
  finally:
    t1 = time.time()
    print('Elapsed: {:.2f} seconds'.format(t1 - t0))



def get_image_from_instagram():
  return np.random.rand(84, 84)

def process_with_numpy(p):
  _process_pic(p)

def process_with_pytorch(p):
  _process_pic(p)

def _process_pic(n_sec):
  print('Processing', end='', flush=True)
  for i in range(10):
    print('.', end='' if i < 9 else 'done!\n', flush=True)
    time.sleep(int(n_sec))

In [13]:
image = get_image_from_instagram()

# Time how long process_with_numpy(image) takes to run
with timer():
  print('Numpy version')
  process_with_numpy(image)

# Time how long process_with_pytorch(image) takes to run
with timer():
  print('Pytorch version')
  process_with_pytorch(image)

Numpy version
Processing.Elapsed: 0.00 seconds


TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
import inspect
print(inspect.getsource(get_image_from_instagram))

import inspect
print(inspect.getsource(process_with_numpy))

import inspect
print(inspect.getsource(process_with_pytorch))

import inspect
print(inspect.getsource(_process_pic))

In [7]:
print(get_image_from_instagram())

[[0.93895442 0.10953234 0.66237965 ... 0.57510436 0.56994636 0.09480082]
 [0.4150124  0.79012833 0.19873347 ... 0.68199046 0.09993139 0.23383015]
 [0.81236416 0.93353212 0.35223494 ... 0.20275667 0.22482392 0.79060799]
 ...
 [0.8980472  0.0881822  0.33013858 ... 0.25644562 0.02456873 0.43363851]
 [0.88158906 0.58143208 0.70555867 ... 0.275297   0.41252381 0.77102682]
 [0.22372162 0.67292449 0.04932159 ... 0.6484499  0.05363619 0.00266056]]
