3D array creation
In the first lesson, you created a `sudoku_game` two-dimensional NumPy array. Perhaps you have hundreds of sudoku game arrays, and you'd like to save the solution for this one, `sudoku_solution`, as part of the same array as its corresponding game in order to organize your sudoku data better. You could accomplish this by stacking the two 2D arrays on top of each other to create a 3D array.

`numpy` is loaded as np, and the `sudoku_game` and `sudoku_solution` arrays are available.

In [4]:
import numpy as np
import matplotlib.pyplot as plt

path=r"D:\\Cursos\\Data_Science_Python\\data_sets\\"
sudoku_game=np.load(path+"sudoku_game.npy")
print("sudoku_game \n",sudoku_game,"\n")
print(type(sudoku_game))

sudoku_solution=np.load(path+"sudoku_solution.npy")
print("sudoku_solution \n",sudoku_solution,"\n")
print(type(sudoku_solution))

sudoku_game 
 [[0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]] 

<class 'numpy.ndarray'>
sudoku_solution 
 [[3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]] 

<class 'numpy.ndarray'>


* Create a 3D array called `game_and_solution` by stacking the two 2D arrays, `sudoku_game` and `sudoku_solution`, on top of one another; in the final array, `sudoku_game` should appear before sudoku_solution.
* Print game_and_solution.

In [6]:
# Create the game_and_solution 3D array
game_and_solution = np.array([sudoku_game ,sudoku_solution] )

# Print game_and_solution
print(game_and_solution)

[[[0 0 5 0 0 9 0 0 1]
  [0 7 0 0 6 0 0 4 3]
  [0 0 6 0 0 2 0 8 7]
  [1 9 0 0 0 7 4 0 0]
  [0 5 0 0 8 3 0 0 0]
  [6 0 0 0 0 0 1 0 5]
  [0 0 3 5 0 8 6 9 0]
  [0 4 2 9 1 0 3 0 0]]

 [[3 2 5 8 4 9 7 6 1]
  [9 7 1 2 6 5 8 4 3]
  [4 3 6 1 9 2 5 8 7]
  [1 9 8 6 5 7 4 3 2]
  [2 5 7 4 8 3 9 1 6]
  [6 8 9 7 3 4 1 2 5]
  [7 1 3 5 2 8 6 9 4]
  [5 4 2 9 1 6 3 7 8]]]
