# Flattening and reshaping
You've learned to change not only array shape but also the number of dimensions that an array has. To test these skills, you'll change `sudoku_game` from a 2D array to a 1D array and back again. Can we trust NumPy to keep the array elements in the same order after being flattened and reshaped? Time to find out.

`numpy` is imported as `np`, and `sudoku_game` is loaded for you.

In [3]:
import numpy as np
import matplotlib.pyplot as plt

path=r"D:\\Cursos\\Data_Science_Python\\data_sets\\"
sudoku_game=np.load(path+"sudoku_game.npy")
print("sudoku_game \n",sudoku_game,"\n")
print(type(sudoku_game))

sudoku_solution=np.load(path+"sudoku_solution.npy")
print("sudoku_solution \n",sudoku_solution,"\n")
print(type(sudoku_solution))

sudoku_game 
 [[0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]] 

<class 'numpy.ndarray'>
sudoku_solution 
 [[3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]] 

<class 'numpy.ndarray'>


- Flatten `sudoku_game` so that it is a 1D array, and save it as `flattened_game`.
- Print the `.shape` of `flattened_game`.

In [4]:
# Flatten sudoku_game
flattened_game = sudoku_game.flatten()

# Print the shape of flattened_game
print(flattened_game.shape)

(72,)


- Reshape the `flattened_game` back to its original shape of nine rows and nine columns; save the new array as `reshaped_game`.

In [6]:
# Flatten sudoku_game
flattened_game = sudoku_game.flatten()

# Print the shape of flattened_game
print(flattened_game.shape)

# Reshape flattened_game back to a nine by nine array
reshaped_game = flattened_game.reshape((8,9))

# Print sudoku_game and reshaped_game
print(sudoku_game)
print(reshaped_game)

(72,)
[[0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]
[[0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]
