# Broadcasting across rows
In the last set of exercises, you used `monthly_industry_multipliers`, to create sales predictions. Recall that `monthly_industry_multipliers` looks like this:

array([[0.98, 1.02, 1.  ],
       [1.00, 1.01, 0.97],
       [1.06, 1.03, 0.98],
       [1.08, 1.01, 0.98],
       [1.08, 0.98, 0.98],
       [1.1 , 0.99, 0.99],
       [1.12, 1.01, 1.  ],
       [1.1 , 1.02, 1.  ],
       [1.11, 1.01, 1.01],
       [1.08, 0.99, 0.97],
       [1.09, 1.  , 1.02],
       [1.13, 1.03, 1.02]])

Assume you're not comfortable being so specific with your estimates. Rather, you'd like to use `monthly_industry_multipliers` to find a single average multiplier for each industry. Then you'll use that multiplier to project next year's sales.

`numpy` is loaded for you as np, and the `monthly_sales` and `monthly_industry_multipliers` arrays are available. The `monthly_sales` columns in order refer to liquor store, restaurant, and department store sales.       

In [2]:
import numpy as np
path=r"D:\\Cursos\\Data_Science_Python\\data_sets\\"
monthly_sales=np.load(path+"monthly_sales.npy")
display(monthly_sales.shape)

monthly_industry_multipliers = np.array([[0.98, 1.02, 1.  ],
       [1.00, 1.01, 0.97],
       [1.06, 1.03, 0.98],
       [1.08, 1.01, 0.98],
       [1.08, 0.98, 0.98],
       [1.1 , 0.99, 0.99],
       [1.12, 1.01, 1.  ],
       [1.1 , 1.02, 1.  ],
       [1.11, 1.01, 1.01],
       [1.08, 0.99, 0.97],
       [1.09, 1.  , 1.02],
       [1.13, 1.03, 1.02]])
display(monthly_industry_multipliers.shape)      

(12, 3)

(12, 3)

* Find the mean sales projection multiplier for each industry; save in an array called `mean_multipliers`.

In [5]:
# Find the mean sales projection multiplier for each industry
mean_multipliers = monthly_industry_multipliers.mean(axis=0)
print(mean_multipliers)

[1.0775     1.00833333 0.99333333]


* Print the shapes of `mean_multipliers` and `monthly_sales` to ensure they are suitable for broadcasting.

In [7]:
# Find the mean sales projection multiplier for each industry
mean_multipliers = monthly_industry_multipliers.mean(axis=0)
print(mean_multipliers)

# Print the shapes of mean_multipliers and monthly_sales
print(mean_multipliers.shape,monthly_sales.shape)

[1.0775     1.00833333 0.99333333]
(3,) (12, 3)


* Multiply each monthly sales value by the mean multiplier you found for that industry; save in an array called `projected_sales`.

In [8]:
# Find the mean sales projection multiplier for each industry
mean_multipliers = monthly_industry_multipliers.mean(axis=0)
print(mean_multipliers)

# Print the shapes of mean_multipliers and monthly_sales
print(mean_multipliers.shape, monthly_sales.shape)

# Multiply each value by the multiplier for that industry
projected_sales = monthly_sales * mean_multipliers
print(projected_sales)

[1.0775     1.00833333 0.99333333]
(3,) (12, 3)
[[ 4454.385      24124.375       8599.28666667]
 [ 4434.99       24073.95833333  9081.05333333]
 [ 5035.1575     27423.64166667 10574.03333333]
 [ 4934.95       25850.64166667 10386.29333333]
 [ 5504.9475     28228.29166667 11223.67333333]
 [ 5399.3525     27647.49166667 10554.16666667]
 [ 5651.4875     27532.54166667 10559.13333333]
 [ 5678.425      27991.33333333 11473.        ]
 [ 5042.7        25196.23333333  9696.92      ]
 [ 5293.7575     26017.01666667 10386.29333333]
 [ 5723.68       25616.70833333 13311.66      ]
 [ 7143.825      28028.64166667 18280.31333333]]
